// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, title, description, metadata) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateConversationParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	UserID      uuid.UUID   `db:"user_id" json:"user_id"`
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, conversation_id, content, role, metadata) VALUES ($1, $2, $3, $4, $5)
`

type CreateMessageParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	ConversationID uuid.UUID  `db:"conversation_id" json:"conversation_id"`
	Content        string     `db:"content" json:"content"`
	Role           string     `db:"role" json:"role"`
	Metadata       []Metadata `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Content,
		arg.Role,
		arg.Metadata,
	)
	return err
}

const deleteConversationByID = `-- name: DeleteConversationByID :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversationByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationByID, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, title, description, metadata, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationWithMessages = `-- name: GetConversationWithMessages :one
SELECT
  c.metadata AS conv_metadata,
  COALESCE(
    (SELECT jsonb_agg(sub ORDER BY sub.created_at ASC)
     FROM (
       SELECT id, conversation_id, role, content, metadata, created_at
       FROM messages
       WHERE conversation_id = c.id
       ORDER BY created_at DESC
       LIMIT $2 OFFSET $3
     ) sub
    ), '[]'::jsonb
  )::jsonb AS messages
FROM conversations c
WHERE c.id = $1
`

type GetConversationWithMessagesParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type GetConversationWithMessagesRow struct {
	ConvMetadata []byte `db:"conv_metadata" json:"conv_metadata"`
	Messages     []byte `db:"messages" json:"messages"`
}

func (q *Queries) GetConversationWithMessages(ctx context.Context, arg GetConversationWithMessagesParams) (GetConversationWithMessagesRow, error) {
	row := q.db.QueryRow(ctx, getConversationWithMessages, arg.ID, arg.Limit, arg.Offset)
	var i GetConversationWithMessagesRow
	err := row.Scan(&i.ConvMetadata, &i.Messages)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT id, user_id, title, description, metadata, created_at FROM conversations WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageCountByConversationID = `-- name: GetMessageCountByConversationID :one
SELECT COUNT(*) FROM messages WHERE conversation_id = $1
`

func (q *Queries) GetMessageCountByConversationID(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageCountByConversationID, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByConversationID = `-- name: GetMessagesByConversationID :many
SELECT id, conversation_id, role, content, metadata, created_at FROM (
  SELECT id, conversation_id, role, content, metadata, created_at FROM messages
  WHERE conversation_id = $1
  ORDER BY created_at DESC
  LIMIT $2 OFFSET $3
) sub ORDER BY created_at ASC
`

type GetMessagesByConversationIDParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversation_id"`
	Limit          int32     `db:"limit" json:"limit"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetMessagesByConversationID(ctx context.Context, arg GetMessagesByConversationIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversationID, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationMetadata = `-- name: UpdateConversationMetadata :exec
UPDATE conversations SET metadata = $2 WHERE id = $1
`

type UpdateConversationMetadataParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Metadata []byte    `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdateConversationMetadata(ctx context.Context, arg UpdateConversationMetadataParams) error {
	_, err := q.db.Exec(ctx, updateConversationMetadata, arg.ID, arg.Metadata)
	return err
}

const updateConversationName = `-- name: UpdateConversationName :exec
UPDATE conversations SET title = $2 WHERE id = $1
`

type UpdateConversationNameParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Title string    `db:"title" json:"title"`
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) error {
	_, err := q.db.Exec(ctx, updateConversationName, arg.ID, arg.Title)
	return err
}
