// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, title, description, metadata) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateConversationParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	UserID      uuid.UUID   `db:"user_id" json:"user_id"`
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, conversation_id, content, role, metadata) VALUES ($1, $2, $3, $4, $5)
`

type CreateMessageParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	ConversationID uuid.UUID  `db:"conversation_id" json:"conversation_id"`
	Content        string     `db:"content" json:"content"`
	Role           string     `db:"role" json:"role"`
	Metadata       []Metadata `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Content,
		arg.Role,
		arg.Metadata,
	)
	return err
}

const deleteConversationByID = `-- name: DeleteConversationByID :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversationByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationByID, id)
	return err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT id, user_id, title, description, metadata, created_at FROM conversations WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversationID = `-- name: GetMessagesByConversationID :many
SELECT id, conversation_id, role, content, metadata, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByConversationID(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationName = `-- name: UpdateConversationName :exec
UPDATE conversations SET title = $2 WHERE id = $1
`

type UpdateConversationNameParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Title string    `db:"title" json:"title"`
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) error {
	_, err := q.db.Exec(ctx, updateConversationName, arg.ID, arg.Title)
	return err
}
