// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, name, file_type, size_bytes, strategy)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, file_type, size_bytes, status, chunk_count, strategy, error_msg, created_at, updated_at
`

type CreateDocumentParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	FileType  string    `db:"file_type" json:"file_type"`
	SizeBytes int64     `db:"size_bytes" json:"size_bytes"`
	Strategy  string    `db:"strategy" json:"strategy"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.Name,
		arg.FileType,
		arg.SizeBytes,
		arg.Strategy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FileType,
		&i.SizeBytes,
		&i.Status,
		&i.ChunkCount,
		&i.Strategy,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, name, file_type, size_bytes, status, chunk_count, strategy, error_msg, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FileType,
		&i.SizeBytes,
		&i.Status,
		&i.ChunkCount,
		&i.Strategy,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, name, file_type, size_bytes, status, chunk_count, strategy, error_msg, created_at, updated_at FROM documents ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FileType,
			&i.SizeBytes,
			&i.Status,
			&i.ChunkCount,
			&i.Strategy,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET status = $2, chunk_count = $3, error_msg = $4
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	Status     string      `db:"status" json:"status"`
	ChunkCount int32       `db:"chunk_count" json:"chunk_count"`
	ErrorMsg   pgtype.Text `db:"error_msg" json:"error_msg"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus,
		arg.ID,
		arg.Status,
		arg.ChunkCount,
		arg.ErrorMsg,
	)
	return err
}
