// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentFlow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Config    AgentFlowConfig    `db:"config" json:"config"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Conversation struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Document struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	FileType   string             `db:"file_type" json:"file_type"`
	SizeBytes  int64              `db:"size_bytes" json:"size_bytes"`
	Status     string             `db:"status" json:"status"`
	ChunkCount int32              `db:"chunk_count" json:"chunk_count"`
	Strategy   string             `db:"strategy" json:"strategy"`
	ErrorMsg   pgtype.Text        `db:"error_msg" json:"error_msg"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversation_id"`
	Role           string             `db:"role" json:"role"`
	Content        string             `db:"content" json:"content"`
	Metadata       []Metadata         `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type News struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Url         string             `db:"url" json:"url"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Research struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Ticker         string             `db:"ticker" json:"ticker"`
	Recommendation string             `db:"recommendation" json:"recommendation"`
	ReferencePrice string             `db:"reference_price" json:"reference_price"`
	Report         StockReport        `db:"report" json:"report"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Watchlist struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Ticker    string             `db:"ticker" json:"ticker"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
