// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        string             `db:"id" json:"id"`
	Content   []byte             `db:"content" json:"content"`
	ThreadID  string             `db:"thread_id" json:"thread_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Thread struct {
	ID          string             `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
