// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestNews = `-- name: GetLatestNews :many
SELECT id, title, url, description, created_at FROM news
WHERE DATE(created_at) = DATE($1::timestamptz)
ORDER BY created_at DESC
`

func (q *Queries) GetLatestNews(ctx context.Context, dollar_1 pgtype.Timestamptz) ([]News, error) {
	rows, err := q.db.Query(ctx, getLatestNews, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNews = `-- name: SaveNews :one
INSERT INTO news (
    title, url, description
) VALUES (
    $1, $2, $3
) RETURNING id, title, url, description, created_at
`

type SaveNewsParams struct {
	Title       string `db:"title" json:"title"`
	Url         string `db:"url" json:"url"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) SaveNews(ctx context.Context, arg SaveNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, saveNews, arg.Title, arg.Url, arg.Description)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
