// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: research_report.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResearchReport = `-- name: CreateResearchReport :one
INSERT INTO research (ticker, recommendation, price, report) VALUES ($1, $2, $3, $4) RETURNING id, ticker, recommendation, price, report, created_at
`

type CreateResearchReportParams struct {
	Ticker         string         `db:"ticker" json:"ticker"`
	Recommendation string         `db:"recommendation" json:"recommendation"`
	Price          string         `db:"price" json:"price"`
	Report         ResearchReport `db:"report" json:"report"`
}

func (q *Queries) CreateResearchReport(ctx context.Context, arg CreateResearchReportParams) (Research, error) {
	row := q.db.QueryRow(ctx, createResearchReport,
		arg.Ticker,
		arg.Recommendation,
		arg.Price,
		arg.Report,
	)
	var i Research
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Recommendation,
		&i.Price,
		&i.Report,
		&i.CreatedAt,
	)
	return i, err
}

const getResearchReportById = `-- name: GetResearchReportById :one
SELECT report FROM research WHERE id = $1
`

func (q *Queries) GetResearchReportById(ctx context.Context, id uuid.UUID) (ResearchReport, error) {
	row := q.db.QueryRow(ctx, getResearchReportById, id)
	var report ResearchReport
	err := row.Scan(&report)
	return report, err
}

const getResearchReports = `-- name: GetResearchReports :many
SELECT id, ticker, recommendation, price, created_at FROM research ORDER BY created_at DESC
`

type GetResearchReportsRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Ticker         string             `db:"ticker" json:"ticker"`
	Recommendation string             `db:"recommendation" json:"recommendation"`
	Price          string             `db:"price" json:"price"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetResearchReports(ctx context.Context) ([]GetResearchReportsRow, error) {
	rows, err := q.db.Query(ctx, getResearchReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResearchReportsRow{}
	for rows.Next() {
		var i GetResearchReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Recommendation,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResearchReport = `-- name: UpdateResearchReport :one
UPDATE research SET recommendation = $2, price = $3, report = $4 WHERE id = $1 RETURNING id, ticker, recommendation, price, report, created_at
`

type UpdateResearchReportParams struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Recommendation string         `db:"recommendation" json:"recommendation"`
	Price          string         `db:"price" json:"price"`
	Report         ResearchReport `db:"report" json:"report"`
}

func (q *Queries) UpdateResearchReport(ctx context.Context, arg UpdateResearchReportParams) (Research, error) {
	row := q.db.QueryRow(ctx, updateResearchReport,
		arg.ID,
		arg.Recommendation,
		arg.Price,
		arg.Report,
	)
	var i Research
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Recommendation,
		&i.Price,
		&i.Report,
		&i.CreatedAt,
	)
	return i, err
}
