// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWatchlistData = `-- name: CreateWatchlistData :one
INSERT INTO watchlist (ticker) VALUES ($1) RETURNING id, ticker, created_at
`

func (q *Queries) CreateWatchlistData(ctx context.Context, ticker string) (Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlistData, ticker)
	var i Watchlist
	err := row.Scan(&i.ID, &i.Ticker, &i.CreatedAt)
	return i, err
}

const deleteWatchlistData = `-- name: DeleteWatchlistData :one
DELETE FROM watchlist WHERE id = $1 RETURNING id, ticker, created_at
`

func (q *Queries) DeleteWatchlistData(ctx context.Context, id uuid.UUID) (Watchlist, error) {
	row := q.db.QueryRow(ctx, deleteWatchlistData, id)
	var i Watchlist
	err := row.Scan(&i.ID, &i.Ticker, &i.CreatedAt)
	return i, err
}

const getWatchlist = `-- name: GetWatchlist :many
SELECT id, ticker, created_at FROM watchlist ORDER BY created_at DESC LIMIT NULLIF($1::int, 0)
`

func (q *Queries) GetWatchlist(ctx context.Context, dollar_1 int32) ([]Watchlist, error) {
	rows, err := q.db.Query(ctx, getWatchlist, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watchlist{}
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(&i.ID, &i.Ticker, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
