networks:
  app-network:
    driver: bridge

services:
  backend:
    # image: backend:latest
    build: .
    ports:
      - "8080:8000"
    networks:
      - app-network
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_market
      POSTGRES_PORT: 5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  db:
    container_name: stock_market_database
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_market
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
